nm = input("Nama\t\t\t: ")
nim = input("NIM\t\t\t: ")
kp = input("Kelas Paralel\t\t: ")
ttl = input("Tempat/Tanggal Lahir\t: ")
al = input("Alamat\t\t\t: ")
hb = input("Hobby\t\t\t: ")
nhp = input("No. HP\t\t\t: ")

print("\nNama\t\t\t:", nm)
print("NIM\t\t\t:", nim)
print("Kelas Paralel\t\t:", kp)
print("Tempat/Tanggal Lahir\t:", ttl)
print("Alamat\t\t\t:", al)
print("Hobby\t\t\t:", hb)
print("No. HP\t\t\t:", nhp)